### ISSUE TITLE
Category Pages Revamp

### ISSUE THREAD

**Issue by titiadecastro** [BYTE-ADMU/itech-ui#34]

**Comment by njtalba5127** [comment]
lezgo titia woohoo

**Comment by njtalba5127** [comment]
⭐  ALL GOODS WITH THIS  ⭐  

Will tackle these na lang on my backend revamp branch. thx @titiadecastro  ⭐  UwU ⭐  

> Review#2 - It wasnt implemented last phase, but the topics above the articles title should:
> 
> 1. display the topic name,
> 2. be a g-link (similar to our router-link but for our gridsome frontend) to lead the user to the topics pages.
> 
> Helpful reference: You can check how it was done on the dashboard where there were buttons to go to the topics pages!
> 
> ![Screenshot 2021-02-22 at 18 18 24](https://user-images.githubusercontent.com/31657420/108694735-66e88700-753a-11eb-9d35-164a76404409.png)

>Question#1 - I am currently revamping the backend (how the frontend gets the data from the strapi server). as you can see, we used the page queries to get the data from our server. This is done from our gridsome-server.js file and basically used axios and graphql to get those data from the server. However we want to change this since it only gets the data at build time (when the app deploys up online).
>Though haven't checked the codes for this branch. You can use the lessons I taught you during training to get the data from our server through axios within that page/component (this is the supposed correct way). This is so when the component loads, it gets the data at realtime instead of my approach (which is wrong :<) to update the website at only build time.
>If you can lang naman OwO u can replace those page queries and do how we did it sa training.

**Comment by njtalba5127** [comment]
⭐ MERGED ⭐
